Api document to pdf
Infotekkers/the-scholars pull request #24
Opened 2021-09-07 15:31 UTC by BarokDG

2021-09-07 18:46 UTC, nati-m-afw requested changes

2021-09-07 18:46 UTC, nati-m-afw commented on server/routes/admin/adminRoutes.js
> -                name: application["fullName"],
@BarokDG this causes a conflict in flutter repo. Its supposed to be _"name"_

2021-09-07 18:46 UTC, nati-m-afw commented on server/routes/admin/adminRoutes.js
> -                name: application["fullName"],
Could you fix it

2021-09-09 06:16 UTC, thomasalemayehu commented
@BarokDG I need this route very soon. Could you finish it early so we can merge it?

2021-09-09 08:27 UTC, merged